import { NextRequest, NextResponse } from "next/server"
import { readFile } from "node:fs/promises"
import { join } from "node:path"

/**
 * Gated playbook delivery endpoint.
 * Only serves the PDF when the request includes a valid session token
 * that was generated by a successful HubSpot form submission.
 *
 * Token format: base64( timestamp:hmac ) — valid for 60 seconds.
 */

const TOKEN_SECRET =
  process.env.PLAYBOOK_TOKEN_SECRET ?? "ist-gtm-playbook-gated-2024"
const TOKEN_TTL_MS = 60_000 // 60 seconds

async function hmac(message: string, secret: string): Promise<string> {
  const enc = new TextEncoder()
  const key = await crypto.subtle.importKey(
    "raw",
    enc.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  )
  const sig = await crypto.subtle.sign("HMAC", key, enc.encode(message))
  return Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("")
}

/** Generate a short-lived token after successful HubSpot submission */
export async function generatePlaybookToken(): Promise<string> {
  const ts = Date.now().toString()
  const sig = await hmac(ts, TOKEN_SECRET)
  return btoa(`${ts}:${sig}`)
}

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get("token")

  if (!token) {
    return NextResponse.json(
      { error: "Missing token" },
      { status: 401 }
    )
  }

  // Decode and validate token
  let ts: string
  let sig: string
  try {
    const decoded = atob(token)
    const parts = decoded.split(":")
    ts = parts[0]
    sig = parts.slice(1).join(":")
  } catch {
    return NextResponse.json(
      { error: "Invalid token" },
      { status: 401 }
    )
  }

  // Check HMAC signature
  const expectedSig = await hmac(ts, TOKEN_SECRET)
  if (sig !== expectedSig) {
    return NextResponse.json(
      { error: "Invalid token signature" },
      { status: 403 }
    )
  }

  // Check TTL
  const age = Date.now() - parseInt(ts, 10)
  if (age > TOKEN_TTL_MS || age < 0) {
    return NextResponse.json(
      { error: "Token expired" },
      { status: 403 }
    )
  }

  // Serve the file
  try {
    const filePath = join(
      process.cwd(),
      "public",
      "assets",
      "InsightsTap-AI-GTM-Strategy-Playbook.pdf"
    )
    const fileBuffer = await readFile(filePath)

    return new NextResponse(fileBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition":
          'attachment; filename="InsightsTap-AI-GTM-Strategy-Playbook.pdf"',
        "Cache-Control": "no-store, no-cache, must-revalidate",
        "X-Content-Type-Options": "nosniff",
      },
    })
  } catch {
    return NextResponse.json(
      { error: "File not found" },
      { status: 500 }
    )
  }
}
